spring.application.name=baseapi

# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/baseapi
spring.datasource.username=postgres
spring.datasource.password=9099
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true